In [1]:
import pandas as pd
from datetime import datetime
import pytz
import unicodedata
import os
import isodate
from googleapiclient.discovery import build
from ytmusicapi import YTMusic

In [5]:
data = '/Users/erinhorbacz/Downloads/YTMusicData/listening_data.csv'
df = pd.read_csv(data)
df['time'] = pd.to_datetime(df['time'])

# Sort by the date column in ascending order
df.sort_values(by='time', inplace=True)
df

,Unnamed: 0,title,titleUrl,time,Name
46881,56597,Creep,https://music.youtube.com/watch?v=zFYEYRcjK2g,2021-12-06 21:10:45.389000+00:00,Radiohead
46880,56596,Save Your Tears,https://music.youtube.com/watch?v=RmYCOm4ehKs,2021-12-06 21:11:55.579000+00:00,The Weeknd
46879,56595,Woman,https://music.youtube.com/watch?v=GnmoJaTWiQE,2021-12-06 21:13:01.578000+00:00,Doja Cat
46878,56594,FourFiveSeconds,https://music.youtube.com/watch?v=5pvcfbf0PXY,2021-12-06 21:14:14.646000+00:00,Rihanna
46877,56593,"The Kid LAROI, Justin Bieber - STAY (Official ...",https://music.youtube.com/watch?v=kTJczUoc26U,2021-12-06 21:41:11.331000+00:00,TheKidLAROIVEVO
...,...,...,...,...,...
4,14,Slow Ride,https://music.youtube.com/watch?v=leVXA1urMg4,2024-11-30 13:05:26.864000+00:00,Foghat
3,13,Deck the Halls,https://music.youtube.com/watch?v=NOBYDwWm9_Q,2024-11-30 13:05:41.303000+00:00,Michael Dulin
2,12,The Christmas Waltz,https://music.youtube.com/watch?v=mRSO2pw8uT0,2024-11-30 13:08:29.824000+00:00,Robert Goulet
1,11,All I Want For Christmas Is You (SuperFestive!...,https://music.youtube.com/watch?v=c5C-dxh4brA,2024-11-30 13:08:55.672000+00:00,Justin Bieber
0,10,Shooting Star (2015 Remaster),https://music.youtube.com/watch?v=5gGjfJHu9wI,2024-11-30 13:09:23.915000+00:00,Bad Company

In [6]:
def collapse(data):
    # Assuming you have other columns like 'artist', 'date', etc.
    collapsed_data = data.groupby('title').size().reset_index(name='count')

    # If you want to keep other columns, you can use `agg()` like so:
    collapsed_data = data.groupby('title').agg(
        count=('title', 'size'),
        artist=('Name', 'first'),  # Assuming you have an 'artist' column
        url=('titleUrl', 'first')   
    ).reset_index()

    return collapsed_data

In [7]:
def get_date_range(dataframe, start_date=None, end_date=None):
    if not start_date and not end_date:
        print('no start date or end date given')
        return 
    utc = pytz.UTC
    if start_date:
        start_date = utc.localize(datetime.fromisoformat(start_date))
    else:
        start_date = dataframe.iloc[0]['time']
    if end_date:
        end_date = utc.localize(datetime.fromisoformat(end_date))
    else:
        end_date = dataframe.iloc[-1]['time']
    # Ensure 'date' column is in datetime format
    dataframe['time'] = pd.to_datetime(dataframe['time'], format='ISO8601')

    # Filter the dataframe
    filtered_df = dataframe[(dataframe['time'] >= start_date) & (dataframe['time'] <= end_date)]

    return collapse(filtered_df)

output = get_date_range(df, '2020-01-01', '2022-11-04')
output

,title,count,artist,url
0,"""Little Drummer Boy"" (Official Music Video) | ...",1,GENTRI,https://music.youtube.com/watch?v=8EaAmXwituc
1,"""Only Human"" - Jonas Brothers (Cover by First ...",1,First To Eleven,https://music.youtube.com/watch?v=EEbhx4_4f2E
2,#icanteven,2,The Neighbourhood,https://music.youtube.com/watch?v=xyDafPK8Z38
3,$TING,1,The Neighbourhood,https://music.youtube.com/watch?v=Zt4EYmXCy4I
4,'Cause I'm A Man,1,Tame Impala,https://music.youtube.com/watch?v=FGPsQedwR1g
...,...,...,...,...
4321,❄️Happy Christmas Music | Relaxing Christmas P...,1,Gingerbread,https://music.youtube.com/watch?v=K6AMwzOAcYk
4322,⦵,1,Coldplay,https://music.youtube.com/watch?v=cZYKKcof30Q
4323,いつも何度でも,6,Makiko Hirohashi,https://music.youtube.com/watch?v=5BAKAXp2sFg
4324,🎄⛄ Christmas JAZZ songs instrumental playlist ...,2,Shin Giwon Piano,https://music.youtube.com/watch?v=6oD1uYkbc9Y
4325,🎅🎄⛄ Smooth & Relaxing ver. Christmas Jazz inst...,4,Shin Giwon Piano,https://music.youtube.com/watch?v=ollqlWr1z8U

In [22]:
API_KEY = 'AIzaSyBsorxCa_L8zPX57Aqz6o9WQTQ_WxeO_zk'
youtube = build('youtube', 'v3', developerKey=API_KEY)
ytmusic = YTMusic()

def normalize_text(text):
    if type(text) == str:
        return unicodedata.normalize('NFKD', text).encode('ASCII', 'ignore').decode('utf-8').lower()
    return 

def get_video_duration(video_id, count):
    video_id = video_id.split("v=")[-1]
    # Fetch video details
    request = youtube.videos().list(
        part='contentDetails',
        id=video_id
    )
    response = request.execute()
    
    # Extract and parse the
    if 'items' in response and len(response['items']) > 0:
        duration = response['items'][0]['contentDetails']['duration']
        # Convert ISO 8601 duration to seconds
        total_seconds = isodate.parse_duration(duration).total_seconds()  * count
        minutes, seconds = divmod(int(total_seconds), 60)
        return f"{minutes:02}:{seconds:02}"  # Format as MM:SS
        # return isodate.parse_duration(duration).total_seconds()
    else:
        print(f"Video ID {video_id} not found.")
        return None

def get_album_from_song(youtube_music_url):
    try:
        # Extract video ID from the URL
        video_id = youtube_music_url.split("v=")[-1].split("&")[0]
        
        song_info = ytmusic.get_song(video_id)
        
        if 'videoDetails' in song_info and 'title' in song_info['videoDetails']:
            song_title = song_info['videoDetails']['title']
        else:
            return "Song title not found"

        # Search for the song to find the album
        search_results = ytmusic.search(song_title, filter="songs")

        for result in search_results:
            if 'album' in result and result['album']:
                return result['album']['name']  # Return album name
        return "Album not found"
    except: 
        print('couldnt get album for', youtube_music_url)
    
def totals_row(dataframe):
    def mmss_to_seconds(mmss):
        minutes, seconds = map(int, mmss.split(':'))
        return minutes * 60 + seconds
    dataframe['total_seconds'] = dataframe['Duration'].apply(mmss_to_seconds)
    number_of_streams = dataframe['count'].sum()
    total_seconds_streamed = dataframe['total_seconds'].sum()
    total_minutes, remaining_seconds = divmod(total_seconds_streamed, 60)
    dataframe = dataframe.drop('total_seconds', axis=1)

    totals_row = {
        'title': 'TOTALS',
        'count': number_of_streams,
        'Duration': f"{int(total_minutes)}:{int(remaining_seconds):02d}"
    }
    for col in dataframe.columns:
        if col not in totals_row:
            totals_row[col] = None 
    totals_df = pd.DataFrame([totals_row])
    dataframe = pd.concat([dataframe, totals_df], ignore_index=True)
    return dataframe

def filter_by_artist(df, artist_name):
    df['normalized_artist'] = df['Name'].apply(normalize_text)
    normalized_search = normalize_text(artist_name)
    if normalized_search in df['normalized_artist'].values:
        directory_path = f'artist_history/{normalized_search}'
        if os.path.isdir(directory_path):
            print('Printing previously collected data')
            artist_dataframe = pd.read_csv(f'artist_history/{normalized_search}/history.csv')
            # artist_dataframe['Album'] = artist_dataframe.apply(lambda row: get_album_from_song(row['url']), axis=1)
            # artist_dataframe.to_csv(f'artist_history/{normalized_search}/history.csv')
            return artist_dataframe
        else:
            print('Collecting data...')
            filtered_df = df[df['normalized_artist'] == normalized_search]
            artist_dataframe = collapse(filtered_df.drop(columns=['normalized_artist']))
            artist_dataframe['Duration'] = artist_dataframe.apply(lambda row: get_video_duration(row['url'], row['count']), axis=1)
            artist_dataframe['Album'] = artist_dataframe.apply(lambda row: get_album_from_song(row['url']), axis=1)
            artist_dataframe = totals_row(artist_dataframe)

            os.makedirs(f'artist_history/{normalized_search}')
            artist_dataframe.to_csv(f'artist_history/{normalized_search}/history.csv')
            return artist_dataframe
    else:
        print(f'There are no artists in listening history with the name {normalized_search}')
        return 

output = filter_by_artist(df, 'mitski')
output

Printing previously collected data
couldnt get album for nan

,Unnamed: 0,title,count,artist,url,Duration,Album
0,0,Abbey,1,Mitski,https://music.youtube.com/watch?v=-wuU_3GmGWs,02:47,Lush
1,1,Bag of Bones,1,Mitski,https://music.youtube.com/watch?v=MvALY9TzINU,04:37,Lush
2,2,Door,1,Mitski,https://music.youtube.com/watch?v=yR0rB7dSH9s,02:13,I've Tried Everything But Therapy (Part 1)
3,3,Eric,1,Mitski,https://music.youtube.com/watch?v=5AH9pU5AZj4,03:18,Unplugged (Live)
4,4,First Love/Late Spring,14,Mitski,https://music.youtube.com/watch?v=WCphVz0ZGns,65:06,Bury Me At Makeout Creek
5,5,Glide (cover),1,Mitski,https://music.youtube.com/watch?v=ur8_4stBye0,03:42,Glide (cover)
6,6,Liquid Smooth,17,Mitski,https://music.youtube.com/watch?v=urdVG-EmosU,48:10,Lush
7,7,Me and My Husband,5,Mitski,https://music.youtube.com/watch?v=TU_Dbxciei8,11:30,Be the Cowboy
8,8,Nobody,4,Mitski,https://music.youtube.com/watch?v=GVZqDCG2VrA,12:56,Only Jesus
9,9,Pearl Diver,1,Mitski,https://music.youtube.com/watch?v=nK_TJLF3a8k,02:45,Lush
10,10,Should've Been Me,1,Mitski,https://music.youtube.com/watch?v=vGAaMCt05cI,03:12,MMO2
11,11,Stay Soft,1,Mitski,https://music.youtube.com/watch?v=ofbEhkO5AGA,03:17,Laurel Hell
12,12,The Only Heartbreaker,1,Mitski,https://music.youtube.com/watch?v=FDb3qY4l-Ks,03:05,Laurel Hell
13,13,Washing Machine Heart,8,Mitski,https://music.youtube.com/watch?v=12rsVkwSsXU,17:12,Be the Cowboy
14,14,Wife,1,Mitski,https://music.youtube.com/watch?v=ccUzg290GME,02:40,2 (2)
15,15,TOTALS,58,NaN,NaN,186:30,None